In [2]:
import torch

What is gradient?
* How much the output changes when we slightly change the input. 
* In math gradient = Derivative

In deep learning the gradient tells us: 
* How much the loss changes if we change the weights.

Then we update weights:

```new weight=old weight−learning rate×gradient```



Gradients are needed for:
* Neural network training
* Backpropagation
* Optimization (like gradient descent)

In [3]:
a = torch.tensor([2.,3.], requires_grad=True) #requires_grad=True, track the gradients . so I can compute gradients later.
b = torch.tensor([6.,4.], requires_grad=True)

In [4]:
f = 3*a**3 - b**2

$f = 3a^3 - b^2$

Using power rule: nx^(n-1)

$\frac{\partial f}{\partial a} = 9a^2$

$\frac{\partial f}{\partial b} = -2b$

In [5]:
f 

tensor([-12.,  65.], grad_fn=<SubBackward0>)

In [6]:
#.backward() without arguments only works if f is a single number (scalar).
f.backward(torch.tensor([1.,1.])) #backward() computes the gradient of f with respect to a and b. The argument is the gradient of f with respect to itself, which is 1.

In [7]:
a.grad 

tensor([36., 81.])

In [8]:
9*a**2 

tensor([36., 81.], grad_fn=<MulBackward0>)

In [9]:
b.grad

tensor([-12.,  -8.])

In [12]:
-2*b 

tensor([-12.,  -8.], grad_fn=<MulBackward0>)