## Tensors

In [7]:
import numpy as np # only work cpu
import torch # work cpu and gpu

In [8]:
arr = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [9]:
tensor = torch.tensor([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])

In [10]:
arr*5

array([[ 5, 10, 15, 20, 25],
       [30, 35, 40, 45, 50]])

In [11]:
tensor*5

tensor([[ 5, 10, 15, 20, 25],
        [30, 35, 40, 45, 50]])

In [12]:
arr.sum()

np.int64(55)

In [13]:
tensor.sum()

tensor(55)

In [15]:
tensor = torch.from_numpy(arr)

In [16]:
tensor 

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [19]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
torch.ones((2, 3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [24]:
np.random.rand(2, 3)

array([[0.81438369, 0.03752344, 0.42620691],
       [0.69770517, 0.46550578, 0.75071058]])

In [25]:
torch.rand(2, 3)

tensor([[0.9613, 0.1243, 0.6647],
        [0.1835, 0.8737, 0.6924]])

In [26]:
arr.shape

(2, 5)

In [27]:
arr.dtype

dtype('int64')

In [28]:
arr.device

'cpu'

In [29]:
tensor.shape

torch.Size([2, 5])

In [30]:
tensor.dtype

torch.int64

In [31]:
tensor.device

device(type='cpu')

In [33]:
arr.to_device('cuda')

ValueError: Unsupported device: cuda. Only 'cpu' is accepted.

In [40]:
tensor = tensor.to('cuda')

In [41]:
tensor.sum() 

tensor(55, device='cuda:0')

In [42]:
tensor.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [43]:
## after all calculations, move back to cpu if needed
tensor = tensor.to('cpu')

In [44]:
tensor.numpy() 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])